### PR TITLE
Add basic docs for release quote-unquote "procedure".

### PR DESCRIPTION
**Pull request by rfk**
Writing this down rather than just responding with it over email.

### CODE REVIEW

**Comment by jrconlin** [comment]
Crud. just saw this. Let me combine it with the RELEASE.md doc, since there are a couple of things I was going to add to that.

**Comment by jrconlin** [comment]
oh, github...

**Comment by rfk** [comment]
Heh, no worries, yours was much more complete than mine :-)

**Comment by rfk** [comment]
Closed in favour of https://github.com/mozilla-services/server-syncstorage/pull/146

**Pull request closed without merging**
