### PR TITLE
Add "extension-storage" to list of standard collections.

### LINKED ISSUE #128: New extension-storage collection will need to be in STANDARD_COLLECTIONS
(And anywhere else along the same lines). We're working on a sync15-based engine for extension-storage, moving it from Kinto. Probably some (small) number of things might be be desirable to change in this repo to prepare for that, although the only one I know of is stuff like the STANDARD_COLLECTIONS list.

### PR DESCRIPTION
**Pull request by rfk**
Fixes #128; r? @thomcc to confirm the correct name for the collection.

### CODE REVIEW

**Comment by pjenvey** [comment]
The last time we added to the std collections @Micheletto noted the ["extension-storage" collection already existed](https://bugzilla.mozilla.org/show_bug.cgi?id=1364005#c3) with what I assume a collection_id > 100 (not 14).

That really complicates adding it to the std list. Should we even bother?

**Comment by rfk** [comment]
> "extension-storage" collection already existed 

Oh wow. I don't know what this might be used for, but it's definitely something other than what @thomcc is about to start using it for. Quite aside from the collection-id issue, whatever is using that collection name seems likely to have problems when the new extension-storage stuff starts clobbering its data in that collection. And we may start seeing impenetrable bug reports when it starts clobbering data that we wrote into that collection.

ISTM we should either convince ourselves that whatever was using that collection name is no longer a significant concern (in which case we can take it over) or we should pick a different name for our own collection. @thomcc thoughts?

**Comment by rfk** [comment]
Per meeting: WONTFIX; @tublitzed is going to follow up on whether we can use the existing "extension-storage" name.

**Comment by tublitzed** [comment]
Per email with @Micheletto and @thomcc we opted to just use a new name. We're going to  [investigate existing collections names](https://bugzilla.mozilla.org/show_bug.cgi?id=1617676) however just to understand how much we should worry about this moving forward/if we need a naming strategy/or to purge collections/etc.

**Pull request closed without merging**
